create table statuses
(
    id bigint generated by default as identity,
    nome varchar(50),
    primary key (id)
);


create table pagamentos
(
    id bigint generated by default as identity,
    valor decimal,
    nome varchar(255),
    numero varchar(19),
    expricacao varchar(7),
    codigo varchar(50),
    status_id bigint,
    pagamento_id bigint,
    pedido_id bigint,
    primary key (id),
    foreign key (status_id) references statuses(id)


);

